#!/bin/bash
PACKAGE=Anaconda3-5.2.0-Linux-x86_64.sh
INSTALLER=https://repo.anaconda.com/archive/$PACKAGE

mkdir anaconda-files
cd anaconda-files
wget $INSTALLER
chmod +x $PACKAGE
./$PACKAGE
cd ..
rm -rf anaconda-files
source ~/.bashrc
conda install jupyter notebook

# sudo yum install python-qt4 -y

