#!/bin/bash
mkdir anaconda-files
cd anaconda-files
wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh
chmod +x Anaconda3-4.4.0-Linux-x86_64.sh
./Anaconda3-4.4.0-Linux-x86_64.sh
cd ..
rm -rf anaconda-files
source ~/.bashrc
conda install jupyter notebook

sudo yum install python-qt4 -y

