#!/bin/bash
sudo rm -rf /opt/flutter
cd /opt
sudo rm -rf flutter_linux_v0.2.8-beta.tar.xz
sudo wget https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_v0.2.8-beta.tar.xz
sudo tar xf flutter_linux_v0.2.8-beta.tar.xz
sudo rm -rf flutter_linux_v0.2.8-beta.tar.xz
sudo tee /etc/profile.d/flutter.sh <<-'EOF'
export PATH=$PATH:/opt/flutter/bin
EOF
sudo chown -R $USER. /opt/flutter

