#!/bin/bash
cd /opt
# http://download.oracle.com/otn-pub/java/jdk/9.0.1+11/jdk-9.0.1_linux-x64_bin.tar.gz
sudo wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/9.0.1+11/jdk-9.0.1_linux-x64_bin.tar.gz"
sudo tar xzf jdk-9.0.1_linux-x64_bin.tar.gz
sudo rm -rf jdk-9.0.1_linux-x64_bin.tar.gz

cd /opt/jdk-9.0.1/

sudo alternatives --install /usr/bin/java java /opt/jdk-9.0.1/bin/java 2
sudo alternatives --config java
sudo alternatives --install /usr/bin/jar jar /opt/jdk-9.0.1/bin/jar 2
sudo alternatives --install /usr/bin/javac javac /opt/jdk-9.0.1/bin/javac 2
sudo alternatives --set jar /opt/jdk-9.0.1/bin/jar
sudo alternatives --set javac /opt/jdk-9.0.1/bin/javac

sudo tee /etc/profile.d/java.sh <<-'EOF'
export JAVA_HOME=/opt/jdk-9.0.1
export JRE_HOME=/opt/jdk-9.0.1/jre
export PATH=$PATH:/opt/jdk-9.0.1/bin:/opt/jdk-9.0.1/jre/bin
EOF


