#!/bin/bash
# mkdir temp
# cd temp

# wget http://nodejs.org/dist/v8.4.0/node-v8.4.0-linux-x64.tar.gz
# sudo tar --strip-components 1 -xzvf node-v* -C /usr/local

sudo yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_8.x | sudo -E bash -

sudo yum install nodejs -y


# cd ..
# rm -rf temp

nodeversion=`node --version`
npmversion=`npm -v`
echo -e "nodesjs version is: $nodeversion"
echo -e "npm version is: $npmversion"
