#!/bin/bash
sudo yum install http://download.virtualbox.org/virtualbox/5.1.26/VirtualBox-5.1-5.1.26_117224_el7-1.x86_64.rpm -y
sudo yum install gcc make -y
sudo yum install kernel-devel -y
sudo /sbin/vboxconfig
